"""initial_schema

Revision ID: 853113cffcb2
Revises: 
Create Date: 2026-04-23 13:49:41.925016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '853113cffcb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('markdown_content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('verification_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_test', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('requirement_pkey'))
    )
    op.create_index(op.f('ix_requirement_is_test'), 'requirement', ['is_test'], unique=False)
    op.create_table('work_packages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('execution_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('implementation_prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verification_prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_test', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], name=op.f('work_packages_requirement_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('work_packages_pkey'))
    )
    op.create_index(op.f('ix_work_packages_status'), 'work_packages', ['status'], unique=False)
    op.create_index(op.f('ix_work_packages_requirement_id'), 'work_packages', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_work_packages_is_test'), 'work_packages', ['is_test'], unique=False)
    op.create_index(op.f('ix_work_packages_execution_order'), 'work_packages', ['execution_order'], unique=False)
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('verification_prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('final_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('failure_reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('failure_details', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_execution_output', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('dead_letter_queue_pkey'))
    )
    op.create_index(op.f('ix_dead_letter_queue_task_id'), 'dead_letter_queue', ['task_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_queue_source_type'), 'dead_letter_queue', ['source_type'], unique=False)
    op.create_index(op.f('ix_dead_letter_queue_source_id'), 'dead_letter_queue', ['source_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_queue_failed_at'), 'dead_letter_queue', ['failed_at'], unique=False)
    op.create_index(op.f('ix_dead_letter_queue_created_at'), 'dead_letter_queue', ['created_at'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('verification_prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('execution_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_test', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('scheduled_after', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('locked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('locked_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_source_type'), 'tasks', ['source_type'], unique=False)
    op.create_index(op.f('ix_tasks_source_id'), 'tasks', ['source_id'], unique=False)
    op.create_index(op.f('ix_tasks_scheduled_after'), 'tasks', ['scheduled_after'], unique=False)
    op.create_index(op.f('ix_tasks_locked_by'), 'tasks', ['locked_by'], unique=False)
    op.create_index(op.f('ix_tasks_locked_at'), 'tasks', ['locked_at'], unique=False)
    op.create_index(op.f('ix_tasks_is_test'), 'tasks', ['is_test'], unique=False)
    op.create_index(op.f('ix_tasks_execution_order'), 'tasks', ['execution_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # WARNING: This drops all tables. Use with caution!
    op.drop_index(op.f('ix_tasks_execution_order'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_test'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_locked_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_locked_by'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_scheduled_after'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_source_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_source_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_dead_letter_queue_created_at'), table_name='dead_letter_queue')
    op.drop_index(op.f('ix_dead_letter_queue_failed_at'), table_name='dead_letter_queue')
    op.drop_index(op.f('ix_dead_letter_queue_source_id'), table_name='dead_letter_queue')
    op.drop_index(op.f('ix_dead_letter_queue_source_type'), table_name='dead_letter_queue')
    op.drop_index(op.f('ix_dead_letter_queue_task_id'), table_name='dead_letter_queue')
    op.drop_table('dead_letter_queue')
    op.drop_index(op.f('ix_work_packages_execution_order'), table_name='work_packages')
    op.drop_index(op.f('ix_work_packages_is_test'), table_name='work_packages')
    op.drop_index(op.f('ix_work_packages_requirement_id'), table_name='work_packages')
    op.drop_index(op.f('ix_work_packages_status'), table_name='work_packages')
    op.drop_table('work_packages')
    op.drop_index(op.f('ix_requirement_is_test'), table_name='requirement')
    op.drop_table('requirement')
